package Enums;
public enum Course {
    // CAS
    BA_ENGLISH_LANGUAGE_STUDIES(Department.COLLEGE_OF_ARTS_AND_SCIENCES),
    BA_FOREIGN_LANGUAGES(Department.COLLEGE_OF_ARTS_AND_SCIENCES),
    BA_POLITICAL_SCIENCE(Department.COLLEGE_OF_ARTS_AND_SCIENCES),
    BS_APPLIED_MATHEMATICS(Department.COLLEGE_OF_ARTS_AND_SCIENCES),
    BS_BIOLOGY(Department.COLLEGE_OF_ARTS_AND_SCIENCES),
    BS_CHEMISTRY(Department.COLLEGE_OF_ARTS_AND_SCIENCES),

    // CBM
    BS_BUSINESS_ADMINISTRATION(Department.COLLEGE_OF_BUSINESS_AND_MANAGEMENT),
    BS_COOPERATIVES_MANAGEMENT(Department.COLLEGE_OF_BUSINESS_AND_MANAGEMENT),
    BS_HOSPITALITY_MANAGEMENT(Department.COLLEGE_OF_BUSINESS_AND_MANAGEMENT),
    BS_TOURISM_MANAGEMENT(Department.COLLEGE_OF_BUSINESS_AND_MANAGEMENT),

    // COC
    BA_BROADCASTING(Department.COLLEGE_OF_COMMUNICATION),
    BA_JOURNALISM(Department.COLLEGE_OF_COMMUNICATION),
    BS_DEVELOPMENT_COMMUNICATION(Department.COLLEGE_OF_COMMUNICATION),

    // COD
    DOCTOR_OF_DENTAL_MEDICINE(Department.COLLEGE_OF_DENTISTRY),

    // COE
    BACHELOR_OF_EARLY_CHILDHOOD_EDUCATION(Department.COLLEGE_OF_EDUCATION),
    BACHELOR_OF_ELEMENTARY_EDUCATION(Department.COLLEGE_OF_EDUCATION),
    BACHELOR_OF_SECONDARY_EDUCATION(Department.COLLEGE_OF_EDUCATION),
    BACHELOR_OF_SPECIAL_NEEDS_EDUCATION(Department.COLLEGE_OF_EDUCATION),

    // CICT
    BACHELOR_OF_LIBRARY_AND_INFORMATION_SCIENCE(Department.COLLEGE_OF_INFORMATION_AND_COMMUNICATIONS_TECHNOLOGY),
    BS_COMPUTER_SCIENCE(Department.COLLEGE_OF_INFORMATION_AND_COMMUNICATIONS_TECHNOLOGY),
    BS_ENTERTAINMENT_AND_MULTIMEDIA_COMPUTING(Department.COLLEGE_OF_INFORMATION_AND_COMMUNICATIONS_TECHNOLOGY),
    BS_INFORMATION_SYSTEMS(Department.COLLEGE_OF_INFORMATION_AND_COMMUNICATIONS_TECHNOLOGY),
    BS_INFORMATION_TECHNOLOGY(Department.COLLEGE_OF_INFORMATION_AND_COMMUNICATIONS_TECHNOLOGY),

    // COM
    DOCTOR_OF_MEDICINE(Department.COLLEGE_OF_MEDICINE),

    // CON
    BS_NURSING(Department.COLLEGE_OF_NURSING),

    // COP
    BACHELOR_OF_CULTURE_AND_ARTS_EDUCATION(Department.COLLEGE_OF_PESCAR),
    BACHELOR_OF_PERFORMING_ARTS(Department.COLLEGE_OF_PESCAR),
    BACHELOR_OF_PHYSICAL_EDUCATION(Department.COLLEGE_OF_PESCAR),
    BS_EXERCISE_AND_SPORTS_SCIENCES(Department.COLLEGE_OF_PESCAR),

    // COL
    JURIS_DOCTOR_PROGRAM(Department.COLLEGE_OF_LAW),

    // ILS
    PRE_ELEMENTARY(Department.INTEGRATED_LABORATORY_SCHOOL),
    ELEMENTARY(Department.INTEGRATED_LABORATORY_SCHOOL),
    JUNIOR_HIGH_SCHOOL(Department.INTEGRATED_LABORATORY_SCHOOL),
    SENIOR_HIGH_SCHOOL(Department.INTEGRATED_LABORATORY_SCHOOL);

    private final Department department;
    
    // Constructor
    private Course(Department department) {
        this.department = department;
    }

    public Department getDepartment() {
        return department;
    }
}
