package Enums;
public enum Department {
    COLLEGE_OF_ARTS_AND_SCIENCES, COLLEGE_OF_BUSINESS_AND_MANAGEMENT,
    COLLEGE_OF_COMMUNICATION, COLLEGE_OF_DENTISTRY,
    COLLEGE_OF_EDUCATION, COLLEGE_OF_INFORMATION_AND_COMMUNICATIONS_TECHNOLOGY,
    COLLEGE_OF_MEDICINE, COLLEGE_OF_NURSING,
    COLLEGE_OF_PESCAR, COLLEGE_OF_LAW,
    INTEGRATED_LABORATORY_SCHOOL
}
